"""Create roles, usuarios and codigos_verificacion tables

Revision ID: 81b395d0567e
Revises: 
Create Date: 2026-09-10 09:39:33.112229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b395d0567e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('tipo_login', sa.Enum('EMAIL', 'TELEFONO', name='tipo_login_enum'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('bloqueado', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(tipo_login = 'EMAIL' AND password_hash IS NOT NULL) OR (tipo_login = 'TELEFONO')", name='ck_usuario_password_requerido_si_email'),
    sa.CheckConstraint('email IS NOT NULL OR telefono IS NOT NULL', name='ck_usuario_email_o_telefono_obligatorio'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('codigos_verificacion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=False),
    sa.Column('canal', sa.Enum('SMS', 'WHATSAPP', name='canal_enum'), nullable=False),
    sa.Column('utilizado', sa.Boolean(), nullable=False),
    sa.Column('expiracion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codigos_verificacion')
    op.drop_table('usuarios')
    op.drop_table('roles')
    # ### end Alembic commands ###

# Alembic no elimina automáticamente los tipos ENUM de PostgreSQL al borrar
    # las tablas que los usan (es una limitación conocida, no un olvido nuestro).
    # Si no los eliminamos acá explícitamente, un downgrade seguido de un upgrade
    # fallaría porque el tipo ya existiría en la base.
    sa.Enum(name='tipo_login_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='canal_enum').drop(op.get_bind(), checkfirst=True)